load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_br_toolchain",
    urls = [
        "https://github.com/skykying/bazel-br-toolchain/archive/V0.0.2.tar.gz",
    ],
    sha256 = "3e0c68235d84c7aef8737f2ea67e12327ab641bec3558ba5241f4968276126c5",
    strip_prefix = "bazel-br-toolchain-0.0.2",
)

load("@bazel_br_toolchain//:deps.bzl", "k8_toolchain_deps","aarch64_toolchain_deps")

k8_toolchain_deps()
aarch64_toolchain_deps()
